# Generated by Django 6.1.1 on 2026-10-02 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKUP_STARTED', 'Pickup started'), ('PICKED_UP', 'Picked up'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tasks', to='donations.donation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tasks', to='organizations.organization')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['volunteer', 'status'], name='pickups_pic_volunte_559692_idx'), models.Index(fields=['status', 'assigned_at'], name='pickups_pic_status_112f97_idx')],
            },
        ),
    ]
