# Generated by Django 5.2.17 on 2026-10-04 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_recipient_workflow'),
        ('organizations', '0001_initial'),
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pickuptask',
            constraint=models.UniqueConstraint(fields=('donation',), name='one_pickup_task_per_donation'),
        ),
    ]
