# Generated by Django 6.1.1 on 2026-10-02 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DONATION_CREATED', 'Donation created'), ('DONATION_ACCEPTED', 'Donation accepted'), ('PICKUP_STARTED', 'Pickup started'), ('FOOD_DELIVERED', 'Food delivered'), ('DONATION_CANCELLED', 'Donation cancelled'), ('EXPIRY_REMINDER', 'Expiry reminder'), ('VOLUNTEER_ASSIGNMENT', 'Volunteer assignment'), ('EMERGENCY_REQUEST', 'Emergency request')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx')],
            },
        ),
    ]
