# Generated by Django 5.2.17 on 2026-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DONATION_CREATED', 'Donation created'), ('DONATION_ACCEPTED', 'Donation accepted'), ('PICKUP_STARTED', 'Pickup started'), ('FOOD_DELIVERED', 'Food delivered'), ('DONATION_CANCELLED', 'Donation cancelled'), ('EXPIRY_REMINDER', 'Expiry reminder'), ('VOLUNTEER_ASSIGNMENT', 'Volunteer assignment'), ('EMERGENCY_REQUEST', 'Emergency request'), ('PICKUP_AVAILABLE', 'Pickup available')], max_length=30),
        ),
    ]
