# Generated by Django 6.1.1 on 2026-10-02 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyFoodRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('people_served', models.PositiveIntegerField()),
                ('urgency', models.PositiveSmallIntegerField(default=3)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('required_before', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to='organizations.organization')),
            ],
            options={
                'ordering': ['required_before'],
                'indexes': [models.Index(fields=['status', 'required_before'], name='emergency_r_status_e60bf7_idx')],
            },
        ),
    ]
