spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resqbite}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:resqbite}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
