# Generated by Django 6.1.1 on 2026-10-02 14:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('VEGAN', 'Vegan'), ('DESSERTS', 'Desserts'), ('BAKERY', 'Bakery'), ('BEVERAGES', 'Beverages'), ('FRUITS', 'Fruits'), ('PACKED_FOOD', 'Packed Food')], max_length=20)),
                ('food_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_unit', models.CharField(default='servings', max_length=30)),
                ('people_served', models.PositiveIntegerField(default=1)),
                ('prepared_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('pickup_address', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('special_instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='donations/')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='donations.donation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FoodSafetyChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freshly_prepared', models.BooleanField()),
                ('properly_packed', models.BooleanField()),
                ('expiry_marked', models.BooleanField()),
                ('food_type_marked', models.BooleanField()),
                ('allergens', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_safety', to='donations.donation')),
            ],
        ),
        migrations.CreateModel(
            name='QRVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('pickup_verified_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_verification', to='donations.donation')),
            ],
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', 'expires_at'], name='donations_d_status_608e66_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['category', 'created_at'], name='donations_d_categor_45f126_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['latitude', 'longitude'], name='donations_d_latitud_5e7301_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='donation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('people_served__gt', 0)), name='donation_people_positive'),
        ),
        migrations.AddIndex(
            model_name='donationrequest',
            index=models.Index(fields=['status', 'created_at'], name='donations_d_status_912e90_idx'),
        ),
        migrations.AddConstraint(
            model_name='donationrequest',
            constraint=models.UniqueConstraint(fields=('donation', 'organization'), name='unique_donation_ngo_request'),
        ),
        migrations.AddConstraint(
            model_name='donationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('donation',), name='one_accepted_request_per_donation'),
        ),
    ]
