# Generated by Django 5.2.17 on 2026-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('servings', 'Servings')], default='servings', max_length=30),
        ),
    ]
