# Generated by Django 5.2.17 on 2026-10-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donation_quantity_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
