# Generated by Django 5.2.17 on 2026-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_donationrequest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
    ]
